In [60]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('zoo1.data')


In [61]:
dataset

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0           1         1         0     0     4     0         0        1     1  
1           1         1         0     0     4     1         0        1     1  
2           1         0         0     1     0     1         0        0     4  
3           1         1         0     0     4     0         0        1     1  
4           1         1         0     0     4     1         0        1     1  
..        ...       ...       ...   ...   ...   ...       ...      ...   ...  
96          1         1         0     0     2     1         0        1     1  
97          0         1         1     0     6     0         0        0     6  
98          1         1         0     0     4     1         0        1     1  
99          0         1         0     0     0     0         0        0     7  
100         1         1         0     0     2     1         0        0     2  

[101 rows x 17 columns]

In [62]:
dataset.head()


hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4  
3         1         0     0     4     0         0        1     1  
4         1         0     0     4     1         0        1     1

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [12]:
X = dataset.values[:,0:16]
Y = dataset.values[:,-1]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3)

NameError: name 'dataset' is not defined

In [15]:
X

NameError: name 'X' is not defined

In [14]:
Y

NameError: name 'Y' is not defined

In [8]:
clf=DecisionTreeClassifier(criterion='entropy')

In [68]:
X_train

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1]])

In [69]:
Y_train

array([4, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 6, 1, 1, 7, 4, 1, 2, 4,
       5, 1, 2, 7, 6, 6, 7, 1, 3, 7, 5, 1, 2, 3, 2, 1, 7, 1, 4, 1, 1, 1,
       1, 5, 5, 1, 7, 2, 7, 3, 2, 1, 6, 1, 6, 7, 2, 6, 4, 4, 1, 1, 4, 1,
       7, 6, 2, 1])

In [70]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [71]:
pred=clf.predict(X_test)

In [72]:
pred

array([6, 1, 1, 2, 7, 2, 2, 4, 2, 1, 1, 1, 2, 1, 5, 4, 1, 5, 1, 1, 1, 2,
       1, 4, 1, 2, 4, 1, 4, 1, 4])

In [73]:
Y_test

array([6, 1, 1, 2, 7, 2, 2, 4, 2, 1, 1, 1, 2, 1, 3, 4, 1, 3, 1, 1, 1, 2,
       1, 4, 1, 2, 4, 1, 4, 1, 4])

In [74]:
print(accuracy_score(Y_test,pred))

0.9354838709677419


In [75]:
print(confusion_matrix(Y_test,pred))

[[14  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  6  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  1]]


In [77]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         7
           3       0.00      0.00      0.00         2
           4       1.00      1.00      1.00         6
           5       0.00      0.00      0.00         0
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         1

    accuracy                           0.94        31
   macro avg       0.71      0.71      0.71        31
weighted avg       0.94      0.94      0.94        31



In [3]:
print(classification_report(y_test, y_pred, target_names=target_names))

NameError: name 'classification_report' is not defined

In [2]:
from sklearn.tree import export_graphviz
from io import StringIO  
from IPython.display import Image  
import pydotplus

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['1','2','3','4','5','6','7'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('zoo.png')
Image(graph.create_png())

ModuleNotFoundError: No module named 'pydotplus'